services:
  oct-srf-classifier:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    volumes:
      - ./models:/app/models
      - ./src:/app/src

    command: 
      bash -c "./scripts/download_sla_model.sh 
            && ./scripts/download_tsa_models.sh 
            && python src/main.py"